config/routes.rb
Research::Application.routes.draw do
  resources :research_areas

  resources :grants

  resources :patents

  resources :publications

  resources :venues

  resources :researchers

  resources :departments

  match 'concepts' => "concepts#index"
  match "concepts/:action", :controller => 'concepts', :action => /[a-zA-Z0-9_]+/i

  root :to => 'home#index'

end

app/models/publication.rb
class Publication < ActiveRecord::Base
  has_and_belongs_to_many :researchers
  has_and_belongs_to_many :research_areas
  belongs_to :venue

  has_many :publications, :through => :research_areas
  has_many :departments, :through => :researchers
  has_many :patents, :through => :research_areas
  has_many :grants, :through => :research_areas

  attr_accessible :name, :venue_id, :publication_date
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @publications }
    end
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
    @publication = Publication.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @publication }
    end
  end

  # GET /publications/new
  # GET /publications/new.json
  def new
    @publication = Publication.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @publication }
    end
  end

  # GET /publications/1/edit
  def edit
    @publication = Publication.find(params[:id])
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(params[:publication])

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render json: @publication, status: :created, location: @publication }
      else
        format.html { render action: "new" }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /publications/1
  # PUT /publications/1.json
  def update
    @publication = Publication.find(params[:id])

    respond_to do |format|
      if params[:publication][:researchers]
        researcher = Researcher.find(params[:publication][:researchers].to_i)
        @publication.researchers << researcher
        @publication.save
        format.json { render json: researcher }
      elsif params[:publication][:research_areas]
        research_area = ResearchArea.find(params[:publication][:research_areas].to_i)
        @publication.research_areas << research_area
        @publication.save
        format.json { render json: research_area }
      elsif @publication.update_attributes(params[:publication])
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication = Publication.find(params[:id])
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_for(@publication) do |f| %>
  <% if @publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
      <% @publication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :venue_id %><br />
    <%= f.select(:venue_id, Venue.all.collect {|d| [ d.name, d.id ] }, { :include_blank => true }) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publications/edit.html.erb
<h1>Editing publication</h1>

<%= render 'form' %>

<%= link_to 'Show', @publication %> |
<%= link_to 'Back', publications_path %>

app/views/publications/index.html.erb
<h1>Listing publications</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Venue</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @publications.each do |publication| %>
  <tr>
    <td><%= publication.name %></td>
    <td><%= Venue.find(publication.venue_id).name %></td>
    <td><%= link_to 'Show', publication %></td>
    <td><%= link_to 'Edit', edit_publication_path(publication) %></td>
    <td><%= link_to 'Destroy', publication, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Publication', new_publication_path %>

app/views/publications/new.html.erb
<h1>New publication</h1>

<%= render 'form' %>

<%= link_to 'Back', publications_path %>

app/views/publications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @publication.name %>
</p>

<p>
  <b>Venue:</b>
  <%= Venue.find(@publication.venue_id).name %>
</p>

<p>
  <b>Researchers:</b>
</p>
<%= form_for @publication, :remote => true, :html => {:id => "researcher-add-form"} do |f| %>
  <%=f.select(:researchers, Researcher.all.collect {|r| [r.name, r.id] }, { :include_blank => true }) %>
  <%=f.submit "Add Researcher" %>
<% end %>
<p>
  <ul id="researchers">
    <% @publication.researchers.each do |researcher| %>
      <li><%=researcher.name %></li>
    <% end %>
  </ul>
</p>

<p>
  <b>Research Areas:</b>
</p>
<%= form_for @publication, :remote => true, :html => {:id => "research-area-add-form"} do |f| %>
  <%=f.select(:research_areas, ResearchArea.all.collect {|r| [r.name, r.id] }, { :include_blank => true }) %>
  <%=f.submit "Add Research Area" %>
<% end %>
<p>
  <ul id="research-areas">
    <% @publication.research_areas.each do |research_area| %>
      <li><%=research_area.name %></li>
    <% end %>
  </ul>
</p>



<%= link_to 'Edit', edit_publication_path(@publication) %> |
<%= link_to 'Back', publications_path %>