config/routes.rb
Research::Application.routes.draw do
  resources :research_areas

  resources :grants

  resources :patents

  resources :publications

  resources :venues

  resources :researchers

  resources :departments

  match 'concepts' => "concepts#index"
  match "concepts/:action", :controller => 'concepts', :action => /[a-zA-Z0-9_]+/i

  root :to => 'home#index'

end

app/models/patent.rb
class Patent < ActiveRecord::Base
  has_and_belongs_to_many :research_areas

  has_many :publications, :through => :research_areas
  has_many :grants, :through => :research_areas
  has_many :researchers, :through => :publications
  has_many :venues, :through => :publications
  has_many :departments, :through => :researchers

  attr_accessible :title
end

app/controllers/patents_controller.rb
class PatentsController < ApplicationController
  # GET /patents
  # GET /patents.json
  def index
    @patents = Patent.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @patents }
    end
  end

  # GET /patents/1
  # GET /patents/1.json
  def show
    @patent = Patent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @patent }
    end
  end

  # GET /patents/new
  # GET /patents/new.json
  def new
    @patent = Patent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @patent }
    end
  end

  # GET /patents/1/edit
  def edit
    @patent = Patent.find(params[:id])
  end

  # POST /patents
  # POST /patents.json
  def create
    @patent = Patent.new(params[:patent])

    respond_to do |format|
      if @patent.save
        format.html { redirect_to @patent, notice: 'Patent was successfully created.' }
        format.json { render json: @patent, status: :created, location: @patent }
      else
        format.html { render action: "new" }
        format.json { render json: @patent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /patents/1
  # PUT /patents/1.json
  def update
    @patent = Patent.find(params[:id])

    respond_to do |format|
      if params[:patent][:research_areas]
        research_area = ResearchArea.find(params[:patent][:research_areas].to_i)
        @patent.research_areas << research_area
        @patent.save
        format.json { render json: research_area }
      elsif @patent.update_attributes(params[:patent])
        format.html { redirect_to @patent, notice: 'Patent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @patent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patents/1
  # DELETE /patents/1.json
  def destroy
    @patent = Patent.find(params[:id])
    @patent.destroy

    respond_to do |format|
      format.html { redirect_to patents_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/patents_helper.rb
module PatentsHelper
end

app/views/patents/_form.html.erb
<%= form_for(@patent) do |f| %>
  <% if @patent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patent.errors.count, "error") %> prohibited this patent from being saved:</h2>

      <ul>
      <% @patent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patents/edit.html.erb
<h1>Editing patent</h1>

<%= render 'form' %>

<%= link_to 'Show', @patent %> |
<%= link_to 'Back', patents_path %>

app/views/patents/index.html.erb
<h1>Listing patents</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @patents.each do |patent| %>
  <tr>
    <td><%= patent.title %></td>
    <td><%= link_to 'Show', patent %></td>
    <td><%= link_to 'Edit', edit_patent_path(patent) %></td>
    <td><%= link_to 'Destroy', patent, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Patent', new_patent_path %>

app/views/patents/new.html.erb
<h1>New patent</h1>

<%= render 'form' %>

<%= link_to 'Back', patents_path %>

app/views/patents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @patent.title %>
</p>

<p>
  <b>Research Areas:</b>
</p>
<%= form_for @patent, :remote => true, :html => {:id => "research-area-add-form"} do |f| %>
  <%=f.select(:research_areas, ResearchArea.all.collect {|r| [r.name, r.id] }, { :include_blank => true }) %>
  <%=f.submit "Add Research Area" %>
<% end %>
<p>
  <ul id="research-areas">
    <% @patent.research_areas.each do |research_area| %>
      <li><%=research_area.name %></li>
    <% end %>
  </ul>
</p>


<%= link_to 'Edit', edit_patent_path(@patent) %> |
<%= link_to 'Back', patents_path %>