config/routes.rb
Research::Application.routes.draw do
  resources :research_areas

  resources :grants

  resources :patents

  resources :publications

  resources :venues

  resources :researchers

  resources :departments

  match 'concepts' => "concepts#index"
  match "concepts/:action", :controller => 'concepts', :action => /[a-zA-Z0-9_]+/i

  root :to => 'home#index'

end

app/models/grant.rb
class Grant < ActiveRecord::Base
  has_and_belongs_to_many :research_areas

  has_many :publications, :through => :research_areas
  has_many :patents, :through => :research_areas
  has_many :researchers, :through => :publications
  has_many :venues, :through => :publications
  has_many :departments, :through => :researchers

  attr_accessible :amount, :date_awarded, :title
end

app/controllers/grants_controller.rb
class GrantsController < ApplicationController
  # GET /grants
  # GET /grants.json
  def index
    @grants = Grant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @grants }
    end
  end

  # GET /grants/1
  # GET /grants/1.json
  def show
    @grant = Grant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @grant }
    end
  end

  # GET /grants/new
  # GET /grants/new.json
  def new
    @grant = Grant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @grant }
    end
  end

  # GET /grants/1/edit
  def edit
    @grant = Grant.find(params[:id])
  end

  # POST /grants
  # POST /grants.json
  def create
    @grant = Grant.new(params[:grant])

    respond_to do |format|
      if @grant.save
        format.html { redirect_to @grant, notice: 'Grant was successfully created.' }
        format.json { render json: @grant, status: :created, location: @grant }
      else
        format.html { render action: "new" }
        format.json { render json: @grant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /grants/1
  # PUT /grants/1.json
  def update
    @grant = Grant.find(params[:id])

    respond_to do |format|
      if params[:grant][:research_areas]
        research_area = ResearchArea.find(params[:grant][:research_areas].to_i)
        @grant.research_areas << research_area
        @grant.save
        format.json { render json: research_area }
      elsif @grant.update_attributes(params[:grant])
        format.html { redirect_to @grant, notice: 'Grant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @grant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grants/1
  # DELETE /grants/1.json
  def destroy
    @grant = Grant.find(params[:id])
    @grant.destroy

    respond_to do |format|
      format.html { redirect_to grants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/grants_helper.rb
module GrantsHelper
end

app/views/grants/_form.html.erb
<%= form_for(@grant) do |f| %>
  <% if @grant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grant.errors.count, "error") %> prohibited this grant from being saved:</h2>

      <ul>
      <% @grant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :date_awarded %><br />
    <%= f.date_select :date_awarded %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grants/edit.html.erb
<h1>Editing grant</h1>

<%= render 'form' %>

<%= link_to 'Show', @grant %> |
<%= link_to 'Back', grants_path %>

app/views/grants/index.html.erb
<h1>Listing grants</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Amount</th>
    <th>Date awarded</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @grants.each do |grant| %>
  <tr>
    <td><%= grant.title %></td>
    <td><%= number_to_currency(grant.amount) %></td>
    <td><%= grant.date_awarded %></td>
    <td><%= link_to 'Show', grant %></td>
    <td><%= link_to 'Edit', edit_grant_path(grant) %></td>
    <td><%= link_to 'Destroy', grant, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Grant', new_grant_path %>

app/views/grants/new.html.erb
<h1>New grant</h1>

<%= render 'form' %>

<%= link_to 'Back', grants_path %>

app/views/grants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @grant.title %>
</p>

<p>
  <b>Amount:</b>
  <%= number_to_currency(@grant.amount) %>
</p>

<p>
  <b>Date awarded:</b>
  <%= @grant.date_awarded %>
</p>

<p>
  <b>Research Areas:</b>
</p>
<%= form_for @grant, :remote => true, :html => {:id => "research-area-add-form"} do |f| %>
  <%=f.select(:research_areas, ResearchArea.all.collect {|r| [r.name, r.id] }, { :include_blank => true }) %>
  <%=f.submit "Add Research Area" %>
<% end %>
<p>
  <ul id="research-areas">
    <% @grant.research_areas.each do |research_area| %>
      <li><%=research_area.name %></li>
    <% end %>
  </ul>
</p>


<%= link_to 'Edit', edit_grant_path(@grant) %> |
<%= link_to 'Back', grants_path %>